import DashboardComponent from '@/components/dashboardComponent'
import Head from 'next/head'
import Image from 'next/image'

export default function Contacto() {
    return (
        <>
            <Head>
                <title>Gabriel Valera | Porfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DashboardComponent>
                <div className='max-w-full min-w-full container'>
                    <div className=" grid ms:grid-cols-2 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2">
                        <div className=' pt-20 mb-6'>
                            <h2 className=' text-6xl text-center mb-6 text-white'>Contacto</h2>
                            <form className=' grid grid-cols-1 ms:grid-cols-2 md:grid-cols-2 gap-6 mx-6 ' id='formularioContacto' name='formularioContacto'>
                                <div className='from-groud'>
                                    <input className=' w-full h-14 px-6 bg-stone-800 focus:bg-stone-700 text-stone-400  rounded-sm' type='text' id='nombre' name='nombre' placeholder='Nombre' />
                                </div>
                                <div className='from-groud'>
                                    <input className='  w-full h-14 px-6 bg-stone-800 focus:bg-stone-700 text-stone-400 rounded-sm' type='email' id='email' name='email' placeholder='Correo' />
                                </div>
                                <div className='from-groud col-span-1 md:col-span-2'>
                                    <textarea className='  w-full h-60 p-6 bg-stone-800 focus:bg-stone-700 text-stone-400 rounded-sm resize-none' id='mensaje' name='mensaje' placeholder='Mensaje'></textarea>
                                </div>
                            </form>
                            <button className=''>hola</button>
                        </div>
                        <div className=' h-screen'>
                            <Image className=' h-full w-full' src="/images/imagen-contacto.webp" alt='wallpaper contacto' width={500} height={500} />
                        </div>
                    </div>
                    {/* imagen-contacto */}
                </div>
            </DashboardComponent>
        </>
    )
}