import DashboardComponent from '@/components/dashboardComponent'
import Head from 'next/head'
import Image from 'next/image'

export default function Skills(){
    return (
        <>
            <Head>
                <title>Gabriel Valera | Porfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <span className=" text-5xl">Sin Contenido</span> */}
            <DashboardComponent>
                <div className='max-w-full min-w-full  container'>
                    <div className=" grid grid-cols-1 ms:grid-cols-2 md:grid-cols-2 lg:grid-cols-2">
                        <section className='pt-20 mb-2 mx-6'>
                            <h2 className=' text-5xl font-bold text-red-600 mb-6'>Skills y <br/> mis experiencias</h2>
                            <p>mucho texto</p>
                        </section>
                        <section className='pt-0 sm:pt-20 mx-6'>
                            <h2>tecnologias</h2>
                            <h2>experiencias</h2>
                        </section>
                    </div>
                </div>
            </DashboardComponent>
        </>
    )
}